StLouisSites/Models/Location.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StLouisSites.Models
{
    public class Location
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string HoursOfOperation { get; set; }
        public string Address { get; set; }
        public string Region { get; set; }
        public List<LocationReview> LocationReviews { get; set; }
        //public Category Category { get; set; }
        public IList<CategoryLocation> CategoryLocations { get; set; }
    }
}

StLouisSites/ViewModels/Locations/LocationCreateViewModel.cs
using StLouisSites.Data;
using StLouisSites.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace StLouisSites.ViewModels.Locations
{
    public class LocationCreateViewModel
    {
      
        [Required]
        public string Name { get; set; }
        [Required]
        [StringLength(200, MinimumLength = 2)]
        public string Description { get; set; }
        public string HoursOfOperation { get; set; }
        public string Address { get; set; }

        [Display(Name="Select one or more categories.")]
        public List<int> CategoryIds { get; set; }
        public List<Category> Categories { get; set; }

        [Required]
        public string Region { get; set; }

        public LocationCreateViewModel() { }

        public LocationCreateViewModel(ApplicationDbContext context)
        {
            //OrderBy(s=>s.name)tells our code to alphabetize results by the name
            this.Categories = context.Categories.OrderBy(s =>s.Name).ToList();
        }

        public void Persist(ApplicationDbContext context)
        {
            Models.Location location = new Models.Location
            {
                Name = this.Name,
                Description = this.Description,
                HoursOfOperation = this.HoursOfOperation,
                Address = this.Address,
                Region = this.Region
                //CategoryId = this.CategoryIds,
                //Categories = this.Categories,
            };
            context.Locations.Add(location);
            //context.SaveChanges();

      
            List<CategoryLocation> categoryLocations = CreateManyToManyRelationships(location.Id);
            location.CategoryLocations = categoryLocations;
            context.SaveChanges();
        }

        private List<CategoryLocation> CreateManyToManyRelationships(int locationId)
        {
            return CategoryIds.Select(catId => new CategoryLocation { LocationId = locationId, CategoryId = catId }).ToList();
        }

        internal void ResetCategoryList(ApplicationDbContext context)
        {
            this.Categories = context.Categories.ToList();
        }
    }
}

StLouisSites/ViewModels/Locations/LocationDetailViewModel.cs
using StLouisSites.Data;
using StLouisSites.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StLouisSites.ViewModels.Locations
{
    public class LocationDetailViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string HoursOfOperation { get; set; }
        public List<LocationReview> LocationReviews { get; set; }


        // we need to get a list of the actively checked IDs for each location when we edit.
        // so we declare a list propety up that we can populate later
        public List<CategoryLocation> ActiveCategoryIds { get; set; }

        // we also need to get a list of all categories
        // so we declare a list propety up that we can populate later
        public List<Category> Categories { get; set; }


        public LocationDetailViewModel() { }


        public LocationDetailViewModel(int Id, ApplicationDbContext context)
        {
            Location location = context.Locations.Find(Id);
            this.Id = location.Id;
            this.Name = location.Name;
            this.Description = location.Description;
            this.HoursOfOperation = location.HoursOfOperation;
            this.LocationReviews = context.LocationReviews.Where(a => a.LocationId == Id).ToList();

           // this.Categories = context.Categories.ToList();

            // populate our placeholder list of activeCategoryId. we query the categorylocations table for categories that contain this locationId
            this.ActiveCategoryIds = context.CategoryLocations.Where(a => a.LocationId == Id).ToList();

            // we then need to convert the ActiveCategoryIds to a type of list<int> we do that with this for loop. 
            // note: this is messy and we can probably do this some other way with less code and less converting from one type to another. 
            List<Category> CategoriesList = new List<Category>();
            foreach (var category in ActiveCategoryIds)
            {
                Category thisSpecificCategory = new Category();

                thisSpecificCategory.Id = category.CategoryId;
                thisSpecificCategory.Name = context.Categories.Where(a => a.Id == category.CategoryId).Select(a => a.Name).Single();

                CategoriesList.Add(thisSpecificCategory); // push this value into our categorylist list above our foreach loop
            }

            //finally..... we can set the forms CategoryIds element to this CategoriesList as it's now the right type (int)
            this.Categories = CategoriesList;

        }

    }
}

StLouisSites/ViewModels/Locations/LocationEditViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using StLouisSites.Data;
using StLouisSites.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace StLouisSites.ViewModels.Locations

{
    public class LocationEditViewModel
    {
        public int LocationId { get; set; }

        [Required]
        public string Name { get; set; }

        // we need to get a list of the actively checked IDs for each location when we edit.
        // so we declare a list propety up that we can populate later
        public List<CategoryLocation> ActiveCategoryIds { get; set; }

        // we also need to get a list of all categories
        // so we declare a list propety up that we can populate later
        public List<Category> Categories { get; set; }

        // we will need this place holder list to push content into after we convert our activecategoryIds list to the right type (int)
        public List<int> CategoryIds { get; set; }

        [Required]
        [StringLength(200, MinimumLength = 2)]
        public string Description { get; set; }
        public string HoursOfOperation { get; set; }
        public string Address { get; set; }

        [Required]
        public string Region { get; set; }

        public LocationEditViewModel() { }

        public LocationEditViewModel(int LocationId, ApplicationDbContext context)
        {
            // populate the form values with data we can easily pull from the database
            Location location = context.Locations.Find(LocationId);
            this.Name = location.Name;
            this.Description = location.Description;
            this.HoursOfOperation = location.HoursOfOperation;
            this.Address = location.Address;
            this.Region = location.Region;
            this.Categories = context.Categories.ToList();

            // populate our placeholder list of activeCategoryId. we query the categorylocations table for categories that contain this locationId
            this.ActiveCategoryIds = context.CategoryLocations.Where(a => a.LocationId == LocationId).ToList();

            // we then need to convert the ActiveCategoryIds to a type of list<int> we do that with this for loop. 
            // note: this is messy and we can probably do this some other way with less code and less converting from one type to another. 
            List<int> CategoriesList = new List<int>();
            foreach (var category in ActiveCategoryIds)
            {
                CategoriesList.Add(category.CategoryId); // push this value into our categorylist list above our foreach loop
            }

            //finally..... we can set the forms CategoryIds element to this CategoriesList as it's now the right type (int)
            this.CategoryIds = CategoriesList;

        }

        public void Persist(int LocationId, ApplicationDbContext context)
        {
            Models.Location location = new Models.Location
            {
                Id = LocationId,
                Name = this.Name,
                Description = this.Description,
                HoursOfOperation = this.HoursOfOperation,
                Address = this.Address,
                Region = this.Region
            };
            context.Update(location);

            List<CategoryLocation> categoryLocations = CreateManyToManyRelationships(location.Id);
            location.CategoryLocations = categoryLocations;
            context.SaveChanges();
        }

        private List<CategoryLocation> CreateManyToManyRelationships(int locationId)
        {
            return CategoryIds.Select(catId => new CategoryLocation { LocationId = locationId, CategoryId = catId }).ToList();
        }

        internal void ResetCategoryList(ApplicationDbContext context)
        {
            this.Categories = context.Categories.ToList();
        }
    }
}

StLouisSites/Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StLouisSites.Data;
using StLouisSites.Models;
using StLouisSites.ViewModels.Categories;
using StLouisSites.ViewModels.Locations;

namespace StLouisSites.Controllers
{
    public class LocationController : Controller
    {
        private ApplicationDbContext context;

        public LocationController(ApplicationDbContext context)
        {
            this.context = context;
        }
           

        public IActionResult Index()
        {
            //List<Location> locations = context.Locations.ToList();
            // where tells the query to get the row that matches the id of the location. This pulls data from the locationReview table 
            //List<Location> locations = context.Locations.Include(a => a.LocationReviews).ToList();
           
            List<LocationListItemViewModel> locations = LocationListItemViewModel.GetLocations(context);

            return View(locations);
        }

        [HttpGet]
        public IActionResult Create()
        {
            LocationCreateViewModel model = new LocationCreateViewModel(context);
            return View(model);
        }

        [HttpPost]
        public IActionResult Create(LocationCreateViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.ResetCategoryList(context);
                return View(model);
            }

            model.Persist(context);
            return RedirectToAction(actionName: nameof(Index));
        }


        [HttpGet]
        public IActionResult Edit(int LocationId)
        {
            return View(new LocationEditViewModel(LocationId, context));
        }

        [HttpPost]
        public IActionResult Edit(int LocationId, LocationEditViewModel location)
        {
            if (!ModelState.IsValid)
            {
                location.ResetCategoryList(context);
                return View(location);
                //return View(new LocationEditViewModel());
            }

            location.Persist(LocationId, context);
            return RedirectToAction(actionName: nameof(Index));
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            // context is the variable name for ApplicationDbContext. Locations is the table in the database
            // where tells the query to get the row that matches the id of the location. This line grabs the location detail information
            // .include tells the query to grab the related reviews for this location from the locationReviews table. This line grabs each review for a location 
            //IList<Location> locations = context.Locations.Where(a => a.Id == id).Include(a => a.LocationReviews).ToList();

            // populate our placeholder list of activeCategoryId. we query the categorylocations table for categories that contain this locationId
            //List<CategoryLocation> activeCategoryIds = context.CategoryLocations.Where(a => a.LocationId == id).ToList();

            //IList<string> activeCategoryNames = new List<string>();


            //foreach (var item in activeCategoryIds)
            //{
            //    string category = context.Categories.Where(a => a.Id == item.CategoryId).Select(a=> a.Name).ToString();
            //    activeCategoryNames.Add( category );

            //}
            //ViewBag.activeCategoryNames = activeCategoryNames;

            // return View(locations);
            return View(new LocationDetailViewModel(id, context));
        }



    }
}

StLouisSites/Controllers/LocationReviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using StLouisSites.Data;
using Microsoft.AspNetCore.Mvc;
using StLouisSites.Models;
using StLouisSites.ViewModels.LocationReviews;

namespace StLouisSites.Controllers
{
    public class LocationReviewController : Controller
    {
        private ApplicationDbContext context;

        public LocationReviewController(ApplicationDbContext context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            List<LocationReview> locationReviews = context.LocationReviews.ToList();
            return View(locationReviews);
        }

        [HttpGet]
        public IActionResult Create(int LocationId)
        {
            Location locationResult = context.Locations.Where(a => a.Id == LocationId).Single();
            ViewBag.locationName =  locationResult.Name;

            return View();
        }

        [HttpPost]
        public IActionResult Create(int LocationId, LocationReviewCreateViewModel model)
        { 
       
            model.Persist(context);
            return RedirectToAction(controllerName: "Location", actionName: "Index");
        }
    }
}

StLouisSites/Views/Location/Create.cshtml
@*@model StLouisSites.Models.Location*@
@model StLouisSites.ViewModels.Locations.LocationCreateViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create Location</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HoursOfOperation " class="control-label">Hours Of Operation</label>
                <input asp-for="HoursOfOperation" class="form-control" />
                <span asp-validation-for="HoursOfOperation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address " class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Region" class="control-label"></label>
                <br/>
                <select asp-for="Region" required class="custom-select custom-select-lg mb-3">
                    <option value=""></option>
                    <option>North St. Louis County</option>
                    <option>South St. Louis County</option>
                    <option>St. Charles County</option>
                    <option>St. Louis City</option>
                    <option>West St. Louis County</option>
                </select>
                <span asp-validation-for="Region" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CategoryIds" class="control-label"></label>
                <div class="scroll-checkbox">
                    @foreach (var category in Model.Categories)
                    {
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" name="CategoryIds" value="@category.Id" />
                            <label class="form-check-label">@category.Name</label>
                        </div>

                    }
                </div>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StLouisSites/Views/Location/Details.cshtml
@*@model IList<StLouisSites.Models.Location>*@
@model StLouisSites.ViewModels.Locations.LocationDetailViewModel


@{
    ViewData["Title"] = "Details";
}




    <h1>@Model.Name</h1>
    <p>
        <b>Hour of Operations:</b><br />
        @Model.HoursOfOperation
    </p>
    <h2>Description</h2>
    <p>@Model.Description</p>

    <hr />

    <h3>Categories</h3>

    <ul>
        @foreach (var category in @Model.Categories)
        {
            <li>@category.Name</li>
        }
    </ul>


    <hr />

    <h3>Reviews</h3>

    <hr />

    <div class="row">
        <div class="col-md-4">

            @foreach (var review in @Model.LocationReviews)
            {
                <dl>
                    <dt>@review.ReviewHeadline</dt>
                    <dd>
                        <div>@review.Rating</div>
                        <div>@review.Review</div>
                    </dd>
                </dl>
            }

        </div>
    </div>


<div>
    @*<a asp-controller="LocationReview" asp-action="Create" asp-route-LocationId="@location.Id">Rate this Location</a>
        <a asp-controller="Location" asp-action="Index">Back to List</a>*@
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StLouisSites/Views/Location/Edit.cshtml
@model StLouisSites.ViewModels.Locations.LocationEditViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Location -  @Model.Name</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="hidden" asp-for="LocationId" />

                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HoursOfOperation" class="control-label">Hours Of Operation</label>
                <input asp-for="HoursOfOperation" class="form-control" />
                <span asp-validation-for="HoursOfOperation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Region" class="control-label"></label>
                <select asp-for="Region" class="form-control">

                    <option value=""></option>
                    <option>North St. Louis County</option>
                    <option>South St. Louis County</option>
                    <option>St. Charles County</option>
                    <option>St. Louis City</option>
                    <option>West St. Louis County</option>

                </select>
                <span asp-validation-for="Region" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CategoryIds" class="control-label"></label>
                <div class="scroll-checkbox">
                    @foreach (var category in @Model.Categories)
                    {
                    <div class="form-check">

                        @if (Model.CategoryIds.Contains(category.Id))
                        {
                            <input type="checkbox" class="form-check-input" name="CategoryIds" value="@category.Id" checked />
                            <label class="form-check-label">@category.Name</label>
                        }
                        else
                        {
                            <input type="checkbox" class="form-check-input" name="CategoryIds" value="@category.Id" />
                            <label class="form-check-label">@category.Name</label>
                        }
                    </div>
                    }
                </div>
            </div>

            <div class="form-group">
                <input type="submit" value="Edit" class="btn btn-primary" />
            </div>
         </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StLouisSites/Views/Location/Index.cshtml
@*@model IList<StLouisSites.Models.Location*@
@model IEnumerable<StLouisSites.ViewModels.Locations.LocationListItemViewModel>


@{
    ViewData["Title"] = "Index";
}

<h1>St. Louis Site Locations:</h1>

<div>

    <hr />
    <table border="1" cellpadding="10">
        <tr>
            <th bgcolor="#cce6ff">Location</th>
            <th width="40%" bgcolor="#cce6ff">Description</th>
            <th bgcolor="#cce6ff">Hours Of Operation</th>
            <th bgcolor="#cce6ff">Average Rating</th>
            <th bgcolor="#cce6ff">Rate</th>
            <th bgcolor="#cce6ff">Edit</th>
        </tr>
        @foreach (var location in Model)

            {
        <tr>
            <td> <a asp-controller="Location" asp-action="Details" asp-route-id="@location.Id">@location.Name</a></td>
            <td>@location.Description</td>
            <td>@location.HoursOfOperation</td>
            @if (@location.LocationReviews.Count > 0)
            {
                <td>@location.AverageRating</td>
            }
            else
            {
                <td>not reviewed</td>
            }
            <td>
                <a asp-controller="LocationReview" asp-action="Create" asp-route-LocationId="@location.Id">Rate</a>
            </td>
            <td>
                <a asp-controller="Location" asp-action="Edit" asp-route-LocationId="@location.Id">Edit</a>
            </td>

        </tr>
            }

    </table>
</div>
<div>
    @*<a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
        <a asp-action="Index">Back to List</a>*@
</div>