StLouisSites/Models/LocationRating.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StLouisSites.Models
{
    public class LocationRating
    {
        public int Id { get; set; }
        public int Rating { get; set; }
        public int LocationId { get; set; }
        public string Review { get; set; }
    }
}

StLouisSites/Controllers/LocationRatingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using StLouisSites.Data;
using Microsoft.AspNetCore.Mvc;

namespace StLouisSites.Controllers
{
    public class LocationRatingController : Controller
    {
        private ApplicationDbContext context;

        public LocationRatingController(ApplicationDbContext context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            List<Location> locations = context.Locations.ToList();
            return View(locations);
        }

        [HttpGet]
        public IActionResult Create(int locationId)
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(int locationId, LocationRatingCreateViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            model.Persist(context);
            return RedirectToAction(controllerName: "Location", actionName: "Index");
        }
    }
}

StLouisSites/Views/LocationRating/Create.cshtml
@model StLouisSites.Models.LocationRating

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Location Rating</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" readonly />
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HoursOfOperation " class="control-label">Hours Of Operation</label>
                <input asp-for="HoursOfOperation" class="form-control" />
                <span asp-validation-for="HoursOfOperation" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StLouisSites/Views/LocationRating/Index.cshtml
@model StLouisSites.Models.LocationRating

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Year)
            </th>
            
            <th>
                @Html.DisplayNameFor(model => model.AverageRating)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumberOfRatings)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Year)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DirectorName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AverageRating)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumberOfRatings)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Rate", "Details", "LocationRating", new { locationId = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>